<?php
 
 use Illuminate\Database\Schema\Blueprint;
 use Illuminate\Database\Migrations\Migration;
 
 class CreateVnasCalendar extends Migration {
 
 	/**
 	 * Run the migrations.
 	 *
 	 * @return void
 	 */
 	public function up()
 	{
 		//DB::statement('DROP VIEW VNAS_CALENDAR');
 		
 		DB::statement( 'CREATE VIEW VNAS_CALENDAR
 						AS
 							SELECT  REL.USER_SK, SCH.SCHEDULE_SK, SCH.CARE_GIVER_ID, SCH.CLIENT_ID,
 							SCH.CALENDAR_TYPE,SCH.CARE_GIVER_FIRST_NME,SCH.CARE_GIVER_LAST_NME,SCH.CARE_GIVER_MOBILE_PH, SCH.CARE_GIVER_OFFICE_PH, SCH.CARE_GIVER_TYPE,
 							SCH.CLIENT_ADDRESS,SCH.CLIENT_CITY, SCH.CLIENT_FIRST_NME, SCH.CLIENT_LAST_NME,SCH.CLIENT_PHONE, SCH.CLIENT_STATE,
 							SCH.CLIENT_ZIP, SCH.SCHEDULE_START_DTTM, SCH.SCHEDULE_END_DTTM, SCH.STS, " "  AS COMMENTS
 						FROM VNAS_VNA_USER_REL REL, VNAS_SCHEDULE SCH
 						WHERE
+							REL.USER_SK IS NOT NULL
 							AND ( REL.VNA_USER_ID = SCH.CLIENT_ID or REL.VNA_USER_ID = SCH.CARE_GIVER_ID )
 							AND SCH.SCHEDULE_START_DTTM  >= DATE(SYSDATE()) - INTERVAL 60 DAY AND SCH.CURRENT_CALENDAR_IND = "Y"
 							AND REL.END_DT IS NULL
 						GROUP BY REL.USER_SK, SCH.SCHEDULE_SK, SCH.CARE_GIVER_ID, SCH.CLIENT_ID,
 								SCH.CALENDAR_TYPE,SCH.CARE_GIVER_FIRST_NME,SCH.CARE_GIVER_LAST_NME,SCH.CARE_GIVER_MOBILE_PH, SCH.CARE_GIVER_OFFICE_PH, SCH.CARE_GIVER_TYPE,
 								SCH.CLIENT_ADDRESS,SCH.CLIENT_CITY, SCH.CLIENT_FIRST_NME, SCH.CLIENT_LAST_NME,SCH.CLIENT_PHONE, SCH.CLIENT_STATE,
 								SCH.CLIENT_ZIP, SCH.SCHEDULE_START_DTTM, SCH.SCHEDULE_END_DTTM, SCH.STS;');
 	}
 
 	/**
 	 * Reverse the migrations.
 	 *
 	 * @return void
 	 */
 	public function down()
 	{
 		DB::statement('DROP VIEW VNAS_CALENDAR');
 	}
 
 }